In [2]:
import jax
import jax.numpy as jnp

In [61]:
input_length = 8
seed = 1
num_hops = 4
key = jax.random.PRNGKey(seed)
permutation = jax.random.permutation(key, jnp.arange(input_length))
zero_index = permutation.argmin()
target = permutation[(zero_index + 1 + num_hops) % input_length]
sequence = jnp.zeros_like(permutation).at[permutation].set(jnp.roll(permutation, -1))

In [62]:
permutation

Array([5, 7, 1, 4, 0, 2, 3, 6], dtype=int32)

In [67]:
jnp.roll(permutation, -zero_index-1)[:num_hops]

Array([2, 3, 6, 5], dtype=int32)

In [63]:
sequence

Array([2, 4, 3, 6, 0, 7, 5, 1], dtype=int32)

In [60]:
target

Array(7, dtype=int32)